export default {
  shoptotal: 'Subtotal',
  promote: 'Sale',
  seckill: 'Flash Sale',
  startIn: 'About to START in',
  endIn: 'About to END in',
  failure: 'Finished',
  allshop: 'All brands',
  sendchina: 'Send China',
  senderAddress: 'Sender address',
  recipientAddress: 'Recipient address',
  couponmoney: 'Discount amount',
  free: 'Free',
  selectInvoice: 'Please select invoice address',
  shippingAddressWarn: 'You address has been changed, due to regional supply reasons, some products may not be delivered.',
  step: {
    cart: 'Cart',
    confirm: 'Confirm',
    pay: 'Pay'
  },
  cart: {
    empty: 'Your cart is empty',
    goshopping: 'Go shopping',
    sendTime: 'Delivery date',
    loading: 'Loading',
    addwish: 'Add to wish list',
    delete: 'Delete',
    deletesome: 'Delete selected items',
    
    selectall: 'Select all',
    choose: '{all} Items（{select} Products）',
    bill: 'Total(Excl. shipping cost)',
    save: 'Saved',
    adt: 'Free delivery on orders over €50 (NL) and €65 (Non-NL); otherwise €6.95 for delivery fee.',
    go: 'Continue',
    already: 'Already in wish list',
    largest: 'The largest stock of goods has been reached'
  },
  confirm: {
    select: 'select',
    disableGoods: 'Unable to dispatch goods',
    pleaseselectdelivery: 'Please select shipping method',
    noadvancedate: 'There is no delivery route for the time limited pre-sale product',
    nofreshdate: 'There is no delivery route for the time limited fresh delivery product',
    redeemCode: 'Redeem code',
    pleaseselecttimerange: 'Please select the time slot',
    redeem: 'Redeem',
    pleaseEnterRedeemCode: 'Please enter redeem code',
    redeemSuccess: 'Redeem succeeded',
    delivery: {
      title: 'Delivery',
      nederlands: {
        title: 'Make a delivery appointment',
        content1: 'Please confirm your order and click [Check Out] to choose your delivery day.',
        content2: 'Thank you for your support！'
      },
      self: {
        title: 'Time of delivery',
        placeholder: 'Please select time of delivery',
        content1: 'Please make the appointment one day before the delivery day to insure your order has been prepared.',
        content2: 'For the pickup-order, the pickup time is 14:00-17:00.'
      },
      pickup: {
        content1: 'The pickup point discount is for MyEUShop normal price items only, and cannot be used with the voucher at the same time',
        agent: 'Please select pickup point',
        agentPoint: 'Please select address pickup point',
        discount: 'discount',
        discountRange: 'discount range:',
        allCategory: 'All Categories',
        selectedCategories:'Selected Categories'
      },
      today: {
        before: 'Please choose another delivery method',
        noMatch: 'Same-day Delivery do not delivery to this postcode yet, please choose another delivery method or postcode.',
        timeLeft: 'Order before',
        timeRight: ', delivered same day.',
        postLeft: 'Currently, the delivery area is',
        postMiddle: 'and',
        postRight: '. We will extend our delivery area soon.',
      },
      dropshipping: {
        title: 'Dropshipping（Send China）',
        content: 'The complete parcel will be sent to your Chinese Recipient’s address directly after picked and packed by us. You can track your parcel on https://www.nlebv.com/.'
      },
      home: {
        title: 'Home Delivery（Send China）',
        content1: 'The complete parcel will be delivered to your home in the Netherlands.',
        content2: "After you personalize the parcel you can go to “My Orders “ to download the sending label and place a pick-up order with NLE to pick up the parcel. You can track your parcel on https://www.nlebv.com/."
      }
    },
    detail: {
      title: 'Product Details',
      edit: 'Edit',
      shopTogether:'ShopTogether',
      voucher: 'Voucher',
      available: 'Available',
      repeat: 'Cannot choose coupons repeatedly'
    },
    shippingInfo: 'Shipping Address',
    invoiceInfo: 'Invoice Information',
    addressInfo: {
      name: 'Name',
      phone: 'Phone',
      postcode: 'Postcode',
      address: 'Address',
      city: 'City',
      country: 'Country'
    },
    remark: {
      title: 'Order Remarks',
      content: 'Please do not note the scheduled delivery time. If you have any questions, please contact the customer service team.'
    },
    line: 'Logistic Service',
    shipping: 'Shipping',
    tax: 'Tax',
    please: 'Please select',
    address:'select address',
    shippingCost: 'Shipping cost',
    bag: 'Shopping Bag',
    submit: 'Check Out',
    shouldPay:'Subtotal',
    selectDeliveryTime: 'Select delivery date',
    cantChangeTime: "Can't change after confirm",
    orderNow: 'Order Now',
    next: 'The next step will be the payment page',
    senderInfo: 'Sender Information',
    recipientInfo: 'Recipient Information',
    onlabel: 'On the label',
    limit: 'The items in cart have exceeded the shipping limit of one parcel, please modify your cart.',
    bill:{
      haveYourOrderPleasePayment: 'Your order has been confirmed.',
      shouldPaymentMoney: 'Total',
      orderDetail: 'Order details',
      orderCode: 'Order number',
      shopTogether: 'Subtotal',
      deliveryAddress: 'Delivery address',
      fullName: 'Full name',
      tel: 'Contact information',
      address: 'Address',
      deliveryMethods: 'Delivery methods',
      takeMethods: 'Delivery method',
      selectPayStyle: 'Payment Method',
      wxPayment: 'Pay with Wechat',
      wxText: 'Use Wechat scan, to scan QR code to complete payment',
      timeOver: 'Time limit will be exceeded after 6 minutes',
      currentTime: 'Current time',
      overTime: 'Expiration time',
      productTotal: 'Product Total',
      handling: 'Handling Fee',
      payTotal: 'Total to pay',
      alipayPayment: 'Alipay payment',
      alipayText: 'To complete the payment, scan QR code to use Alipay',
      balancePayment: 'Pay from account balance',
      balanceAbout: 'NOTE: All transactions are processed only when your NLE account balance exceeds €20. If you hit the back button during the transaction, the cookie will automatically reject your transaction even if you inputted the correct information.',
      AccountBalance: 'Account balance',
      payImmediately: 'Pay now',
      iDealPayment: 'Pay with iDeal',
    },
    noshipping: 'Please select shipping address',
    nosender: 'Please select sender information',
    norecipient: 'Please select recipient information',
    noDelivery: 'Please select delivery method',
    noline: 'Please select shipping service'
  },
  success: {
    Paying: 'Paying',
    paymentsuccess: 'Payment successful',
    Paymenttimeout: 'Payment time out please refresh the page',
  },
  pickup: {
    addressWarn: 'All delveries are fully booked, please try a new address',
    selectDate: 'Book your delivery',
    pleaseSelectDate: 'Please book your delivery',
    excess: 'FULL',
    pickup: 'Available',
    notLine: 'Non',
    choose: 'Delivery day',
    comfirm: 'Confirm'
  }
}