export default {
  'myaccount': 'My Account',
  'myorder': 'My Orders',
  'seckill': 'Flash Sale',
  'invoiceList': 'Invoice List',
  'myvouchers': 'My Vouchers',
  'messages': 'Messages',
  'myaddress': 'My Address',
  'shippingaddress': 'Shipping Address',
  'reciveAddress': 'Address list',
  'senderinfo': 'Sender Information',
  'recipientinfo': 'Recipient Information',
  'invoiceinformation': 'Invoice Information',
  'orderrefund': 'Order Refund',
  'wishList': 'Wish List',
  'password': 'Change Password',
  'logout': 'Log Out',
  'sale': 'Sale',
  'noorder': '0 order',
  'nowish': '0 wish',
  'suretologout': 'Are you sure to log out?',
  'allshop': 'All brands',
  'sendername': 'Sender',
  'senderaddress': 'Sender address',
  'recipientname': 'Recipient',
  'recipientaddress': 'Recipient address',
  'emailPlaceholder': 'Email',
  'free': 'Free',
  'hot': 'Hot',
  'mycenter': {
    'editinfo': 'Edit info',
    'welcome': 'Hello, welcome to MyEUShop',
    'clientnumber': 'Client number',
    'contactinfo': 'Tel',
    'balance': 'Balance',
    'voucher': 'Vouchers',
    'wishproduct': 'Wish product',
    'wishshop': 'Wish shop',
    'shipaddress': 'Ship address',
    'unpaid': 'Unpaid',
    'unreciived': 'Unreceived',
    'unevaluated': 'Unevaluated',
    'refund': 'Refund',
    'lastestorder': 'Latest order',
    'viewmore': 'View more',
    'editaccount': 'Edit my account',
    'photo': 'Photo',
    'fullname': 'Full name',
    'phone': 'Telephone',
    'country': 'Country',
    'postcode': 'Postal code',
    'birthday': 'Birthday',
    'door': 'Door number',
    'city': 'City',
    'street': 'Street',
    'tel': 'Phone number',
    'mywish': 'My wish'
  },
  'orderlist': {
    'orderdetails': 'Order details',
    'continueshopping': 'Buy Again',
    'expressdetail': 'Look logistics',
    'commentorder': 'Comment',
    'agree': 'Agree',
    'refundnotice': 'Refund Notice',
    'refundnoticecontent1': '1. Coupons cannot be refunded if your order is paid with them.',
    'refundnoticecontent2': '2. Commission fees charged by the third-party payment gateway cannot be refunded if you pay via Wechat or Alipay.',
    'refundnoticecontent3': '3. It takes 2-5 working days to get your money back after applying for a refund.',
    'refundnoticecontent4': '4. For more details, please refer to our after-sales service terms or customer service staff.',
    'cancelorder': 'Cancel order',
    'tips': 'Notice',
    'cancelapp': 'Cancel appointment',
    'cancelcontent1': 'We are sorry that the delivery address cannot be changed if you cancel.Please contact our customer service if you need to change your delivery address. Thank you so much!',
    'cancelcontent2': 'We are sorry that the delivery address cannot be changed if you remake the appointment.Please contact our customer service if you need to change your delivery address. Thank you so much!',
    'makeapp': 'Make appointment',
    'deleteorder': 'Delete',
    'downloadinvoice': 'Download invoice',
    'immediatepayment': 'Pay now',
    'ordernumber': 'Order number',
    'ordertime': 'Order time',
    'applyforreturn': 'Request a refund',
    'refunddetails': 'Refund details',
    'allorders': 'All orders',
    'pleaseinputorder': 'Please input order number',
    'paymentresttime': 'Remaining time to pay',
    'timeover': 'Order has been cancelled',
    'appointment': 'Pickup Date',
    'cancelpickup': 'Cancel Pickup'
  },
  'orderdetails': {
    'ordersubmit': 'Order submit',
    'paid': 'paid',
    'delivering': 'delivering',
    'delivered': 'delivered',
    'distance': 'Distance',
    'deliveryname': 'Delivery name',
    'postnlDelivery': 'Postnl number',
    'deliveryaddress': 'Delivery address',
    'deliverystyle': 'Delivery methods',
    'thegoodsstyle': 'Delivery method',
    'expresscode': 'Tracking number',
    'apptime': 'Time of delivery',
    'lookexpress': 'Check track & trace',
    'goodssubtotal': 'Subtotal of goods',
    'shoppingbag': 'Shopping bag',
    'freight': 'Shipping cost',
    'couponmoney': 'Discount amount',
    'havepaymentmoney': 'Amount has been paid',
    'shouldpaymentmoney': 'Total',
    'track': 'Track',
    'time': 'Time',
    'progress': 'Progress',
    'noexpressinformation': 'No delivery information',
    'tax': 'Tax',
    'globalnumber': 'Global tracking number',
    'downloadlabel': 'Download Label'
  },
  'orderoperation': {
    'shipaddress': 'Shipping address',
    'deliverytime': 'Delivery time',
    'pleaseselect': 'Please select address',
    'pleaseselecttimerange': 'Please select the time slot',
    'warehouseaddress': 'Warehouse address',
    'orderdelivery1': 'Please make the appointment one day before the delivery day to insure your order has been prepared.',
    'orderdelivery2': 'For the pickup-order, the pickup time is 14:00-18:00.',
    'mycomment': 'My comment',
    'ordercoment1': 'How about giving me an evaluation!'
  },
  'invoicelist': {
    'invoicenumber': 'Invoice number',
    'batchdownload': 'Batch download',
    'timerange': 'Time range',
    'invoicevalue': 'Invoice value',
    'inverse': 'Inverse',
    'operation': 'Operation'
  },
  'messageslist': {
    'mymessage': 'My message',
    'allmessage': 'All',
    'systemmessage': 'System',
    'customermessage': 'Customer service',
    'ordermessage': 'Order',
    'expressmessage': 'Delivery',
    'shopmessage': 'Seller',
    'cartmessage': 'Cart'
  },
  'returndetails': {
    'refundlist': 'Refund list',
    'applyforreturn': 'Request a refund',
    'returnreason': 'Reason for refund',
    'submitapplyfor': 'Submit application',
    'returndetail': 'Refund details',
    'returnsuccess': 'Refund successfully',
    'returnmoney': 'Refund amount',
    'enteryouaccoundpleaselook': 'Will be return to your account, please check your account',
    'therefundcheckisnotapproved': 'Refund not approved',
    'approvalofrefund': 'Refund approved',
    'ifshopagree': 'When seller has been agreed',
    'sevendealtoyoureturn': 'will deal your refund request within 7 days',
    'ifshoprefuse': 'When seller has been refused',
    'needtoyoucontactservice': 'Contact customer service for further details',
    'ifshopernodeal': 'When the seller has not been processed',
    'youcanapplyforcustomer': 'You can apply for customer service intervention',
    'applyforservice': 'Apply for service',
    'returninstructions': 'Return instructions',
    'shopinstructions': 'Shopping instructions',
    'applyfortime': 'Application time'
  },
  'wishlist': {
    'wishlist': 'Wish list',
    'wishproduct': 'Wish product',
    'wishshop': 'Wish shop',
    'suretodeletewish': 'Are you sure to cancel collection '
  },
  'refund': {
    'selectRefund': 'Select product to refund',
    'goodsCanNotRefund': 'The product cannot request for refund',
    'selectAll': 'Select all',
    'pleaseSelectRefund': 'Please select product to refund',
    'refundMethod': 'Refund method',
    'plaseSelectMethod': 'Select refund method',
    'bankRefund': 'Bank transfer',
    'cashRefund': 'Prepaid Voucher',
    'bankNo': 'Bank number',
    'bankName': 'Name bank account',
    'bankInfo': 'Please ensure the name and bank account you entered are correspond, otherwise, it may cause to failure refund transaction.',
    'maxRefund': 'Max refund amount',
    'shippingFee': ',shipping fee will not be refunded.',
    'selectBank': 'Refund to bank account: We will review and refund money to your bank account within 10 working days.',
    'selectCash': 'Refund with prepaid voucher: we will review and send a prepaid voucher to your voucher list within 2 working days. The prepaid voucher is available to use on all products with no minimum spending limit.',
    'pleaseEnterAmount': 'Please enter refund amount',
    'pleaseEnterReason': 'Please enter refund reason',
    'pleaseUploadPhoto': 'Please upload photo',
    'selectReundMethod': 'Please select refund method',
    'pleaseEnterBank': 'Please enter your bank account number',
    'pleaseEnterName': 'Please enter your full name',
    'refundAmount': 'Refund Amount',
    'refunding': 'Processing Refund',
    'refundSuccess': 'Refund Succeed',
    'pleaseselect': 'Please select'
  }
}