export default {
	myaccount: 'My Account',
	myorder: 'My Orders',
	seckill: 'Flash Sale',
	invoiceList: 'List of invoices',
	myvouchers: 'My Vouchers',
	messages: 'Messages',
	myaddress: 'My Address',
	shippingaddress: 'Address',
	reciveAddress: 'Delivery Address',
	senderinfo: 'Sender information',
	recipientinfo: 'Recipient information',
	invoiceinformation: 'Invoice Address',
	orderrefund: 'My Refund',
	wishList: 'My Wish List',
	password: 'Change Password',
	logout: 'Log out',
	sale: 'On Sale',
	noorder: 'No order now',
	nowish: 'Nothing in the wish list now',
	suretologout: 'Are you sure to log out?/',
	allshop: 'All stores',
	sendername: 'Sender Name',
	senderaddress: 'Sender Address',
	recipientname: 'Recipient Name',
	recipientaddress: 'Recipient Address',
	emailPlaceholder: 'Please enter E-mail address',
	free: 'Free',
	hot: 'Hot',
	mycenter: {
		editinfo: 'Modify your profile',
		welcome: 'Hi, welcome to MyEUShop',
		clientnumber: 'Customer Number',
		contactinfo: 'Telephone Number',
		balance: 'Balance',
		voucher: 'Vouchers',
		wishproduct: 'Items in wish list',
		wishshop: 'Brands in wish list',
		shipaddress: 'Recipient Address',
		unpaid: 'To be paid',
		unreciived: 'To be received',
		unevaluated: 'To be commented',
		refund: 'Refund',
		lastestorder: 'Latest orders',
		viewmore: 'View more',
		editaccount: 'Edit your account',
		photo: 'Profile picture',
		fullname: 'Name',
		phone: 'Telephone',
		country: 'Country',
		postcode: 'Postcode',
		birthday: 'Date of Birth',
		door: 'House Number',
		city: 'City',
		street: 'Subdistrict',
		tel: 'Telephone Number',
		mywish: 'My Wish List'
	},
	orderlist: {
		orderdetails: 'Order Details',
		continueshopping: 'Buy more',
		expressdetail: 'Tracking order',
		commentorder: 'Comment Now',
		agree: 'Accept',
		refundnotice: 'Refund Notices',
		refundnoticecontent1: '①If a voucher is used for your order, the voucher cannot be returned to you.',
		refundnoticecontent2:
			'②If you use Alipay or WeChat to pay, the handling fee will not be refunded because the it is charged by a third-party platform.',
		refundnoticecontent3:
			'③After you apply for a refund, the Customer Service will review the refund for you in time, and the Finance will refund you within 2-5 working days.',
		refundnoticecontent4:
			'④For more information on refund, please check after-sales services or consult Customer Service.',
		cancelorder: 'Cancel order',
		tips: 'Notice',
		cancelapp: 'Cancel reservation',
		cancelcontent1:
			'We are sorry that the delivery address cannot be changed if you cancel.Please contact our customer service if you need to change your delivery address. Thank you so much!',
		cancelcontent2:
			'We are sorry that the delivery address cannot be changed if you remake the appointment.Please contact our customer service if you need to change your delivery address. Thank you so much!',
		makeapp: 'Select another delivery date',
		deleteorder: 'Delete order',
		downloadinvoice: 'Invoice downloading',
		immediatepayment: 'Pay Now',
		ordernumber: 'Order Number',
		ordertime: 'Time of order',
		applyforreturn: 'Apply for Refund',
		refunddetails: 'Refund details',
		allorders: 'All orders',
		pleaseinputorder: 'Enter order number',
		paymentresttime: 'Remaining time for payment',
		timeover: 'Payment timeout, order cancelled',
		appointment: 'Pickup Date',
		cancelpickup: 'Cancel Pickup'
	},
	orderdetails: {
		ordersubmit: 'Submit',
		paid: 'Checkout',
		delivering: 'Delivery',
		delivered: 'Sign for acknowledgement of receipt',
		distance: 'away from you',
		deliveryname: 'Name',
		postnlDelivery: 'Tracking Number',
		deliveryaddress: 'Delivery Address',
		deliverystyle: 'Method of Delivery',
		thegoodsstyle: 'Method of Pick-up',
		expresscode: 'Tracking Number',
		apptime: 'Delivery Date',
		lookexpress: 'Tracking order',
		goodssubtotal: 'Total stores',
		shoppingbag: 'Packing fee',
		freight: 'Freight',
		couponmoney: 'Discount Amount',
		havepaymentmoney: 'Actual Amount',
		shouldpaymentmoney: 'Amount payable',
		track: 'Tracking order',
		time: 'Time',
		progress: 'Location and work progress',
		noexpressinformation: 'No trackiing results',
		tax: 'Tax',
		globalnumber: 'Tracking Number (International Express)',
		downloadlabel: 'Download the label'
	},
	orderoperation: {
		shipaddress: 'Delivery information',
		deliverytime: 'Delivery Date',
		pleaseselect: 'Please select',
		pleaseselecttimerange: 'Please select the time slot',
		warehouseaddress: 'Warehouse Address',
		orderdelivery1: 'Please reserve one day in advance to allow us to pick the goods for you.',
		orderdelivery2:
			'Goods can be picked up at 14:00-18:00 p.m. by presenting the screeshot of the order placed over your phone.',
		mycomment: 'My comments',
		ordercoment1: 'Hello dear, how about giving me an evaluation！'
	},
	invoicelist: {
		invoicenumber: 'Invoice number',
		batchdownload: 'Batch downloading',
		timerange: 'Time Slot',
		invoicevalue: 'Invoice Value',
		inverse: 'Invert Selection',
		operation: 'Operation'
	},
	messageslist: {
		mymessage: 'My Messages',
		allmessage: 'All messages',
		systemmessage: 'System Message',
		customermessage: 'Customer service',
		ordermessage: 'Order',
		expressmessage: 'Delivery',
		shopmessage: 'Seller',
		cartmessage: 'Cart'
	},
	returndetails: {
		refundlist: 'List of refunds',
		applyforreturn: 'Apply for Refund',
		returnreason: 'Refund Reason',
		submitapplyfor: 'Submit application',
		returndetail: 'Refund details',
		returnsuccess: 'Refund Successfully',
		returnmoney: 'Refund amount',
		enteryouaccoundpleaselook: 'please check',
		therefundcheckisnotapproved: 'Refund Rejected',
		approvalofrefund: 'Refund accepted',
		ifshopagree: 'If accepted by the Seller,',
		sevendealtoyoureturn: 'the refund will be handled within 7 days',
		ifshoprefuse: 'If the refund is rejected by the Seller,',
		needtoyoucontactservice: 'you are required to contact Customer Service',
		ifshopernodeal: 'If tue refund is not handled by the Seller,',
		youcanapplyforcustomer: 'you may contact customer service',
		applyforservice: 'Apply for service',
		returninstructions: 'Refund notices',
		shopinstructions: 'Seller description',
		applyfortime: 'Time of application'
	},
	wishlist: {
		wishlist: 'List of items in wish list',
		wishproduct: 'Items in wish list',
		wishshop: 'Brands in wish list',
		suretodeletewish: 'Are you sure to remove it from wish list?'
	},
	refund: {
		selectRefund: 'Select product to refund',
		goodsCanNotRefund: 'Unable to refund',
		selectAll: 'All',
		pleaseSelectRefund: 'Please select product to refund',
		refundMethod: 'Refund Methods',
		plaseSelectMethod: 'Select refund method',
		bankRefund: 'Bank transfer',
		cashRefund: 'Rechargeable vouchers',
		bankNo: 'Bank card number',
		bankName: 'Name for the bank card',
		bankInfo:
			'Please ensure the name you entered is the same one for the bank card, otherwise, the refund may fail.',
		maxRefund: 'Enter amount no more than',
		shippingFee: 'The refunded amount will not include handling fee',
		selectBank:
			'Refund to bank account: We will review and refund money to your bank account within 10 working days.',
		selectCash:
			'Refund with rechargeable voucher: we will review and send a rechargeable voucher equivalent to the refunded amount to your vouchers. The rechargeable voucher is available to be used on all products with no minimum spending limit. The refund will be normally reviewed and made within 2 working days',
		pleaseEnterAmount: 'Please enter the refund amount',
		pleaseEnterReason: 'Please state the reason',
		pleaseUploadPhoto: 'Please upload pictures',
		selectReundMethod: 'Please select the method of refund',
		pleaseEnterBank: 'Please enter bank card number',
		pleaseEnterName: 'Please enter Name',
		refundAmount: 'Refund amount',
		refunding: 'Refunding',
		refundSuccess: 'Refund Successfully',
		pleaseselect: 'Please select'
	}
};
