export default {
  shoptotal: '店铺合计',
  promote: '促销',
  seckill: '秒杀',
  startIn: '距离秒杀开始仅剩',
  endIn: '距离秒杀结束仅剩',
  failure: '失效',
  allshop: '所有店铺',
  senderAddress: '发件地址',
  recipientAddress: '收件地址',
  couponmoney: '优惠金额',
  sendchina: '',
  free: '赠',
  selectInvoice: '请选择发票地址',
  shippingAddressWarn: '地址更改，因地域供货原因，部分商品可能无法派送。',
  step: {
    cart: '购物车',
    confirm: '订单确认',
    pay: '订单支付'
  },
  cart: {
    empty: '您的购物车还没有商品',
    goshopping: '去逛逛',
    loading: '正在加载中',
    sendTime: '派送日期',
    addwish: '加入收藏',
    delete: '删除',
    deletesome: '批量删除',
    selectall: '全选',
    choose: '共计商品{all},已选择商品{select}',
    bill: '合计（不含运费）',
    save: '已节省',
    adt: '全荷兰地区满50欧配送，非荷兰地区满65欧配送。若未满免费配送额，收取6.95欧配送费。',
    go: '去结算',
    already: '已收藏',
    largest: '已到商品最大库存'
  },
  confirm: {
    select: '请选择',
    disableGoods: '无法派送商品',
    pleaseselectdelivery: '请选择配送方式',
    pleaseselecttimerange: '请选择时间段',
    noadvancedate: '限定派送日期的预售商品，对应您的地址没有派送路线',
    nofreshdate: '限定派送日期的新鲜速派商品，对应您的地址没有派送路线',
    redeemCode: '兑换码',
    redeem: '兑换',
    redeemSuccess: '兑换成功',
    pleaseEnterRedeemCode: '请输入兑换码',
    delivery: {
      title: '配送方式',
      nederlands: {
        title: '预约送货',
        content1: '完成信息确认，点击提交订单后，预约您的派送日期。',
        content2: '感谢支持！'
      },
      self: {
        title: '预约时间',
        placeholder: '请选择预约时间',
        content1: '提前一天预约，让我们有时间为您配好货。',
        content2: '下午14:00-17:00可以提货，显示手机下单截图即可。'
      },
      pickup: {
        content1: '代理收货点折扣不与优惠券同时使用，且只参与欧亚商城自营正价商品',
        agent: '请选择代理收货点',
        agentPoint: '请选择代理收货点地址',
        discount: '折扣',
        discountRange: '折扣范围：',
        allCategory: '全部分类',
        selectedCategories: '部分分类'
      },
      today: {
        before: '请选择其他派送方式。',
        noMatch: '不在配送范围内，请选择其他收货地址。',
        timeLeft: '我们会为下单时间在',
        timeRight: '前的客户当天送达他的订单。',
        postLeft: '目前仅支持邮编为：',
        postMiddle: '和',
        postRight: '的地区。更多支持地区会陆续开放。',
        
      },
      dropshipping: {
        title: '直邮中国',
        content: '直接代发是直接代发到中国。具体是下单成功后，我们会将专业打包好的商品直接配送到您填写的中国收件人的地址。您可以在NLE网站追踪该包裹的物流状态。'
      },
      home: {
        title: '中转代发',
        content1: '中转代发是先送到荷兰地址再代发到中国。具体是下单成功后，系统会自动预约最近的送货时间，我们将商品配送到您的荷兰地址。您收到商品后，可以在“订单详情”里下载寄到中国的物流面单，然后点击“预约取件”，预约NLE司机上门取件。您可以在NLE网站查询该包裹的物流。 ',
        content2: ''
      }
    },
    detail: {
      title: '商品详情',
      edit: '修改购物车',
      voucher: '优惠券',
      available: '当前可用',
      repeat: '不能重复选择优惠券'
    },
    shippingInfo: '派件信息',
    invoiceInfo: '发票信息',
    remark: {
      title: '订单备注',
      content: '请不要备注预约送货时间，具体时间视单量和路况而定。如有问题请联系客服。'
    },
    line: '路线',
    shipping: '运费',
    tax: '税费',
    please: '请选择',
    address:'请选择地址',
    shippingCost: '运费',
    bag: '包装袋',
    submit: '提交订单',
    shouldPay:'应付',
    selectDeliveryTime: '请选择预约时间',
    cantChangeTime: '预约时间选择好之后不可更改',
    orderNow: '确定下单',
    next: '下一步将跳到付款页面',
    orderNote:'订单备注',
    senderInfo: '发件信息',
    recipientInfo: '收件信息',
    onlabel: '面单上显示的信息',
    limit: '当前购物车里的商品内容物超出单个包裹可邮寄范围，请您修改购物车商品数量。',
    addressInfo: {
      name: '姓名',
      phone: '电话',
      postcode: '邮编',
      address: '地址',
      city: '城市',
      country: '国家'
    },
    bill:{
      haveYourOrderPleasePayment: '您的订单已生成，请尽快完成支付！',
      shouldPaymentMoney: '应付金额',
      orderDetail: '订单详情',
      orderCode: '订单编号',
      shopTogether: '店铺合计',
      deliveryAddress: '派送地址',
      fullName: '姓名',
      tel: '联系方式',
      address:'地址',
      deliveryMethods: '派送方式',
      selectPayStyle: '请选择付款方式',
      wxPayment: '微信支付',
      wxText: '使用微信扫一扫, 扫描二维码完成支付',
      timeOver: '时效性截止：六分钟后失效',
      currentTime: '当前时间',
      overTime: '截止时间',
      productTotal: '商品总价',
      handling: '手续费',
      payTotal: '合计金额',
      alipayPayment: '支付宝付款',
      alipayText: '使用支付宝扫一扫, 扫描二维码完成支付',
      balancePayment: '账号余额付款',
      balanceAbout: '请确认您支付后，账上余额还留有20欧以上，这20欧是NLE邮寄包裹的押金，无法用于支付，谢谢您的理解！',
      AccountBalance:'账户余额',
      payImmediately:'立即支付',
      iDealPayment:'iDeal付款',
    },
    noshipping: '请选择派件地址',
    nosender: '请选择发件信息',
    norecipient: '请选择收件信息',
    noDelivery: '请选择派送方式',
    noline: '请选择路线'
  },
  success: {
    Paying: '正在支付中',
    paymentsuccess: '支付成功',
    Paymenttimeout: '支付超时，请重新刷新页面',
  },
  pickup: {
    addressWarn: '当前地址目前无可预约日期，请切换地址',
    selectDate: '请选择预约派送日期',
    pleaseSelectDate: '请选择派送日期',
    excess: '已约满',
    pickup: '可预约',
    notLine: '无派送',
    choose: '已选择',
    comfirm: '确认日期'
  }
}