export default{
    register:{
        title: '申请成为商家',
        english:'English',
        chinese:'中文',
        email: '邮箱',
        checkEmail:'请输入邮箱地址',
        rightEmail:'请输入正确的邮箱地址',
        eushopEmail:'MyEUShop的注册邮箱',
        eushopPwd:'MyEUShop的注册密码',
        logoSize:'图片尺寸260x140',
        bannerSize:'图片尺寸1140x300',
        bannerInfo:'有广告图销量更好哦',
        password: '密码',
        rightWord:'请输入密码',
        shopZn:'店铺中文名称',
        rightZn:'请输入中文店铺名称',
        shopEn:'店铺英文名称',
        rightEn:'请输入英文店铺名称',
        number:'客服电话',
        rightNum:'请输入客服电话',
        qq:'客服QQ',
        wechat:'客服微信',
        Introduce:'店铺介绍',
        logo:'店铺LOGO',
        rightLogo:'请上传店铺LOGO',
        banner:'店铺广告图',
        confirm:'确认',
        cancel:'取消',
        upload:'点击上传',
    }
    
}